### ISSUE TITLE
TODO: Add wheelchair accessibility limitations to workflow

### ISSUE THREAD

**Issue by zneedell** [LBNL-UCB-STI/PILATES#25]
Here's a list of changes that need to happen for us to successfully reproduce the wheelchair accessibility runs within PILATES:

- [x] **Add wheelchair attribute to ActivitySim inputs**. The easiest way to do this is probably to just modify the persons table in the `custom_mpo_06197001_model_data.h5` urbansim data input file to include a wheelchair attribute (important to make sure we do this for the correct year). The starting file is available [here](https://beam-outputs.s3.amazonaws.com/pilates-outputs/urbansim/custom_mpo_06197001_model_data.h5), and BEAM expects a column in the persons.csv file titled `in_wheelchair` that is set to either True or False. @nazanin87. 
- [x] **Make sure wheelchair attribute is visible to ActivitySim in PILATES**. Probably will be true by default if it's in the h5 file but worth confirming. @zneedell 
- [x] **Change ASim config to use different wait times depending on disability status**. Let's create a new branch of the [asim config repo](https://github.com/LBNL-UCB-STI/activitysim-configs-sfbay) where we modify the wait times in the trip and tour mode choice. I think the first step is to create a target `requires_wheelchair` by adding a line to the `annotate_persons` script [here](https://github.com/LBNL-UCB-STI/activitysim-configs-sfbay/blob/main/configs/annotate_persons.csv). As far as I can tell this script should have access to all of the columns that are in the `persons` file in the input h5 directory. I think doing this should make the boolean `requires_wheelchair` attribute available whenever we're doing mode choice. The wait times are constructed [here](https://github.com/LBNL-UCB-STI/activitysim-configs-sfbay/blob/main/configs/trip_mode_choice_annotate_trips_preprocessor.csv#L48-L50) and [here](https://github.com/LBNL-UCB-STI/activitysim-configs-sfbay/blob/a4067f30c4dec02e764665873f3b7e825cd3f2a9/configs/tour_mode_choice_annotate_choosers_preprocessor.csv#L35-L40). We'd need to change the existing logic, e.g. 
> `odt_skims['RH_SOLO_WAIT'] * (1.0 - odt_skims['RH_SOLO_REJECTIONPROB']) + TNC_missed_trip_penalty * odt_skims['RH_SOLO_REJECTIONPROB']` 

to something that accounts for the `requires_wheelchair` attribute, so e.g. something like 
> `np.where(df.requires_wheelchair,odt_skims['RH_SOLO_ACCESSIBLE_WAIT'] * (1.0 - odt_skims['RH_SOLO_ACCESSIBLE_REJECTIONPROB']) + TNC_missed_trip_penalty * odt_skims['RH_SOLO_ACCESSIBLE_REJECTIONPROB'],odt_skims['RH_SOLO_WAIT'] * (1.0 - odt_skims['RH_SOLO_REJECTIONPROB']) + TNC_missed_trip_penalty * odt_skims['RH_SOLO_REJECTIONPROB'])`

I'm hoping that `requires_wheelchair` will automatically make it over to `df`, but it might take some additional work if not. @nazanin87

- [x] **Update PILATES to create separate wheelchair / non-wheelchair skims**. New pilates branch [`wheelchair-ridehail-skims`](https://github.com/LBNL-UCB-STI/PILATES/tree/wheelchair-ridehail-skims/pilates)
- [x] **Upload new BEAM docker image with wheelchair code**. There is now a BEAM image on dockerhub at the location `zaneedell/beam:0.wheelchair.0`
- [x] **Create beam data repo branch with wheelchair inputs**. There is now a beam-data repo [`pilates-wheelchair`](https://github.com/LBNL-UCB-STI/beam-data-sfbay/tree/pilates-wheelchair)
- [x] **Set up PILATES scenarios with different fleet penetration of accessible vehicles**. @nazanin87 with help from @cristian-poliziani

**Comment by cristian-poliziani** [comment]
Great, thanks Zach and Cristian. I'll take a look at the scripts and
documents by tomorrow's meeting.

**Comment by zneedell** [comment]
Draft PR that should allow this on the skims end in PILATES: https://github.com/LBNL-UCB-STI/PILATES/pull/26

**Comment by cristian-poliziani** [comment]
That sounds great, thank you Zach for putting together all that and @Nazanin
Rezaei ***@***.***> feel free to write to me or plan a meeting with
me when needed.

Cristian
