### ISSUE TITLE
TODO: nice-to-have updates for next set of runs

### ISSUE THREAD

**Issue by zneedell** [LBNL-UCB-STI/PILATES#34]
- [x] Switch to generating skims in BEAM in the omx format natively (and then merging them in the postprocessor). BEAM PR here: https://github.com/LBNL-UCB-STI/beam/pull/3736
- [x] Consider failed trips when merging skims from different iterations. When the ratio of impossible:completed trips is too high, we need to make sure asim knows that those ODs aren't served by transit. We probably want a penalization function that is weak when there are a few impossible trips but very high when there are no completed trips. BEAM PR here: https://github.com/LBNL-UCB-STI/beam/pull/3735
- [x] Longer term goal: Be able to start a PILATES run in a new city (e.g. Seattle) starting with only default skims, and have it fill in real skim values as people in BEAM try more ODs
- [x] Pipe household vehicle ownership from ATLAS -> BEAM via vehicles.csv
